#!/usr/local/bin/python3
import tkinter as tk
from tkinter import *
import subprocess




root = Tk()
root.config(bg="#282828")
root.geometry("800x38")
root.update_idletasks()	
windowWidth = root.winfo_width()
windowHeight = root.winfo_height()
positionRight = int(root.winfo_screenwidth()/2 - windowWidth/2)
positionDown = int(root.winfo_screenheight()/2 - windowHeight/2 - 200)
root.geometry("+{}+{}".format(positionRight, positionDown))


def get_string(event):
    string = entry.get()
    a = string.split()
    b = "+".join(a)
    root.destroy()
    command = f'https://duckduckgo.com/lite/search?q={b}'
    subprocess.run(["xterm", "-e", "lynx", command])
        
entry = Entry(root, bg="grey", fg="#ebdbb2", font=("ubuntu", 15), width=70)
entry.pack(pady=3, padx=3, fill="x")
entry.focus()
entry.bind('<Return>', get_string)

root.mainloop()
